name: Build & Run Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: List files
        run: ls -la

      - name: Build and run compose
        run: docker compose up --build -d
